steps:
  - label: ":docker: Build Docker imag"
    command:
      - "docker build -t Buildkite ."
    plugins:
      - docker#v3.7.0:
          build:
            file: Dockerfile
            context: .
          image: Buildkite
          tags:
            - latest
