steps:
  - label: ":docker: Build Docker imge"
    command:
      - "docker build -t docker-buildkite ."
    plugins:
      - docker#v3.7.0:
          build:
            file: Dockerfile
            context: .
          image: nginx:latest
          tags:
            - latest
